services:

  my-web-app:
    build: .
    container_name: application
    ports:
      - "8088:8080"
    links:
      - my-app-db

  my-app-db:
    build: ./db
    container_name: db
    expose:
      - "5432"