services:

  my-web-app:
    build: app
    container_name: application
    ports:
      - "8088:8088"
    links:
      - my-app-db

  my-app-db:
    build: db
    container_name: db
    expose:
      - "5432"
    volumes_from:
      - my-app-db-data

  my-app-db-data:
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - /var/lib/postgresql/data